//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_SA_TT
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CID { get; set; }
        public string TEXT_ADDR { get; set; }
        public string TEXT_ADDR_NRM { get; set; }
        public string TEXT_ADDR_OTHER { get; set; }
    }
}
