//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_USERS
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
