//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_CALENDAR_DM
    {
        public Nullable<decimal> ID { get; set; }
        public decimal OBJECT_ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> ALLDAY { get; set; }
        public string URL { get; set; }
    }
}
